name: pokemon_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  provider: ^4.1.0
  flutter_state_notifier: ^0.4.0
  freezed_annotation:
  flutter_swiper: ^1.1.6

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  build_runner: ^1.10.0
  freezed: ^0.10.8
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/
